### ISSUE TITLE
Target for Azure Storage

### ISSUE THREAD

**Issue by jasonwilliams200OK** [mapbox/node-pre-gyp#134]
Hello, we have our projects hosted on Azure. We are planning to build some nodejs utilities of hybrid nature: node-js with C++ add-ons and .NET using [edge](https://github.com/tjanczuk/edge).

Is it possible to use [Azure Storage for Node.js](http://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-blob-storage/) as a storage to host binaries build by node-pre-gyp? If not, please provide the steps if someone has successfully configured it.

It would be much appreciated if Azure Store is added as an alternative service provider to AWS, and the how-to info is reflected on docs.

**Comment by springmeyer** [comment]
Yes, this should be doable now without any changes to node-pre-gyp. The `install` command that is used when users install your binaries uses `https` and does not depend on AWS S3. That is the only critical piece. So just configure the [host](https://github.com/mapbox/node-pre-gyp#host) parameter to point to an http/web accessable location hosted on azure and your users will be able to get your binaries.


As far as getting the binaries published. Well, it should be as simple as running `node-pre-gyp package` locally and then manually pushing the tarball to your remote location. But with a little bit of effort you can automate that yourself because it is easy to programmatically interact with node-pre-gyp in order to write your own publish script. You can run `node-pre-gyp reveal` to get access to all the info you'd need to script uploading your binaries to a custom location on azure. A workflow could look like this:

```sh
# build and package binary module
./node_modules/.bin/node-pre-gyp build package
# then validate the package
./node_modules/.bin/node-pre-gyp testpackage
# next grab the path to the tarball package
LOCAL_BINARY=$(./node_modules/.bin/node-pre-gyp reveal staged_tarball --silent)
REMOTE_BINARY=$(./node_modules/.bin/node-pre-gyp reveal hosted_tarball --silent)
# ... then use whatever azure upload tool you want to move the LOCAL_BINARY to the REMOTE_BINARY
```

Let me know if I need to make anything more clear.

**Comment by jasonwilliams200OK** [comment]
Thanks for the information @springmeyer. We will try to adhere by your instructions. 
Maybe it is Azure team responsibility to add documentation for their customers. For that matter, I have opened an issue to their repo: https://github.com/Azure/azure-content/issues/2432.

Or maybe our company should buy Amazon S3 bucket, since that is something which is trending..

**Comment by springmeyer** [comment]
@jasonwilliams200OK - yes, I highly recommend using Amazon S3 - you are likely talking about less than a few bucks a month to host a node-pre-gyp binary on S3.

**Comment by jasonwilliams200OK** [comment]
@springmeyer, I agree. Actually its not about the price, as there is no different [AWS-S3](http://aws.amazon.com/s3/pricing/) vs. [AzS](http://azure.microsoft.com/en-us/pricing/details/storage/) (instead Azure is bit cheaper), but its about the services and community support. Ruby and Node.js gems/packages are mostly Amazon-first and since we are experimenting with these runtimes to gauge our options for future, I think its better to be a hipster (S3) than waiting for other party (Azure) to grow large in certain community.
