### ISSUE TITLE
Suppor specifying Node ABI version via options

### ISSUE THREAD

**Issue by joshhunt** [mapbox/node-pre-gyp#167]
I'm using a module which uses `node-pre-gyp` (`node-sqlite3`) and executing it on AWS's Lambda platform, where you can't control the version of Node that's used.

When the function is executed, I'm getting this error:

```
Error: Cannot find module '/var/task/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node'
```

node-v11 doesn't exist, because when I run `cd node_modules/sqlite3/; node-pre-gyp install --target_platform=linux` on my machine to download the linux bindings, it gets the node-v14 bindings.

Can you please support passing in this version via options so I don't have to manually download the bindings?

**Comment by springmeyer** [comment]
For context of ABI `v11` refers to the `process.versions.modules` value and `11` signifies node v0.10.x. You can see the mapping by running this script within node-pre-gyp:

```
$ node scripts/latest-by-abi.js 
0.8.28 { node_abi: 1, v8: '3.11' }
0.10.38 { node_abi: 11, v8: '3.14' }
0.11.7 { node_abi: 12, v8: '3.20' }
0.11.10 { node_abi: 13, v8: '3.22' }
0.12.4 { node_abi: 14, v8: '3.28' }
1.0.4 { node_abi: 42, v8: '4.1' }
1.8.2 { node_abi: 43, v8: '4.1' }
2.3.1 { node_abi: 44, v8: '4.2' }
```

So, I think then that AWS is running node v0.10.x. And therefore you are hitting this problem because you are running v0.12.x locally and packaging up a zip with binaries for node v0.12.x (which clearly will not work). So, you have two options:

1) install node v0.10.x locally and build your package that way
2) stick with node v0.12.x but pass `--target=0.10.33` (it could also be `--target=0.10.25` or `--target=0.10.0` or any node version that has an ABI of `11`)

I gather you were thinking there should be a way to request the ABI of `11` explicitly? I'm not sure this is a good idea / more complex. Let me know any additional thoughts.

**Comment by joshhunt** [comment]
I ended up using nvm to go with approach one, but I'll update build scripts to use method 2.

Thanks.
