### ISSUE TITLE
devDependencies

### ISSUE THREAD

**Issue by farfromrefug** [mapbox/node-pre-gyp#215]
I am some devDependencies that are only used during compilation.
While developping my module this works fine as i do ```npm install``` and dev dependencies are installed.

however when i use my module as a dependency of another project the ```devDependencies```  does not seem to be installed.
Especially i would expect ```node-pre-gyp install --fallback-to-build``` to run ```npm install``` and thus get the ```devDependencies```

So i am force to have everything as a ```dependencies``` which i don't want cause then it gets packed/published (electron for example)
Am i doing something wrong?

**Comment by springmeyer** [comment]
This is intentional. The devDependencies are only needed by developers of packages. So the idea is that the devDependencies of node-pre-gyp will be selectively included as devDependencies of your module that is packaged with node-pre-gyp. This triggers a bit of work, but avoids unnecessary dependencies being automatically brought in for some projects that publish in different ways (e.g. aws vs github releases).
