### ISSUE TITLE
relative paths not being handled properly

### ISSUE THREAD

**Issue by tjwebb** [mapbox/node-pre-gyp#219]
https://github.com/mapbox/node-pre-gyp/blob/master/lib/install.js#L126

If I invoke `npm install` from outside the source directory, this does not work.

Side note: there's no reason to use `fs` module here. Simply `require()` the package.json file.

**Comment by springmeyer** [comment]
> If I invoke npm install from outside the source directory, this does not work.

That is by design in the sense that: `node-pre-gyp` needs to be able to open the `package.json` at a predicable location and `npm` will put the current working directory inside the modules source directory such that `./package.json` is the right path.

What scenario are you hitting that does not work? In that scenario how can node-pre-gyp know where the package.json is?

**Comment by springmeyer** [comment]
> Side note: there's no reason to use fs module here. Simply require() the package.json file.

Done in 8179047

**Comment by springmeyer** [comment]
reverted, this broke for some reason...

```
stderr: node-pre-gyp ERR! UNCAUGHT EXCEPTION 
  node-pre-gyp ERR! stack Error: Cannot find module './package.json'
  
```

**Comment by tjwebb** [comment]
> What scenario are you hitting that does not work?

I filed about a half dozen mapnik-related issues in the respective project repos relating to build issues. This was one of them.

Sure `require()` doesn't work if you just slam `./package.json` in there. That would just be trading one form of this problem for another. You need to use `__dirname` or `require.main` to properly compute the relative paths instead of assuming the location (`process.cwd()`, basically) that the script is invoked from.
