### ISSUE TITLE
Native support for GitHub releases

### ISSUE THREAD

**Issue by chearon** [mapbox/node-pre-gyp#225]
I'm a bit confused why AWS is required for node-pre-gyp publishing, GitHub says that there is [no limit](https://help.github.com/articles/distributing-large-binaries/) to the bandwidth for Releases. And the limit on file sizes is like 2GB. Sounds like a pretty good deal to me!

It doesn't seem sustainable to require everyone to maintain and pay for their own separate release servers, and with Releases they are centralized and easily findable.

I played around with node-pre-gyp-github but it's buggy, it seems like it's time for node-pre-gyp to support publishing to GitHub releases natively.

Thoughts?

**Comment by bchr02** [comment]
Since you're calling me out... What's so buggy with node-pre-gyp-github? Can you be specific? 

It should do what your looking to do? And I'm actively maintaining it. 

By the way, I have always wanted node-pre-gyp to natively support github released until recently. I now think it would be best if it didn't directly handle this or S3 publishing and instead have those as seperate modules so that the core would be lighter and not have as many dependencies.  The package maintainers would then only need these extra modules for the purpose of publishing and not the end users. 

Those are my thoughts.

**Comment by chearon** [comment]
@bchr02 sorry, I should have made issues in your project :)

I noticed it crashes if in package.json, `repository` is specified as a string instead of an object. It also seems to expect `build/stage` instead of `build/Release`? Dunno a ton about node-gyp but I thought that was the default build location for releases.

And then it was crashing and not publishing if you have subdirectories inside of that - looks like it was trying to do a filename call on folders and an exception is thrown for that.

Architecturally yeah it would be nice to have S3 and Releases as modules, but I can't see a good reason to not use Releases, so it would be great if that worked out of the box

**Comment by springmeyer** [comment]
Please contribute to node-pre-gyp-github and making it more reliable. I agree that s3 support should also be moved to a module, but I don't have time to work on this right now.

**Comment by chearon** [comment]
Both AppVeyor and Travis have really good support for publishing to GitHub releases, so I just started using that instead. I imagine many other people must be doing that too

**Comment by springmeyer** [comment]
@chearon - sounds good.
