### ISSUE TITLE
Bug in 'node-pre-gyp' while using any command on Snappy Ubuntu Core on Raspberry PI 2

### ISSUE THREAD

**Issue by OwenLearnsToCode** [mapbox/node-pre-gyp#238]
Running Snappy Ubuntu Core on Raspberry pi 2 Model B with ARMv7 processor. I am trying to use 'node-pre-gyp install --fallback-to-build' after downloading the node-pre-gyp module, which is used for installing the serialport module. However the following error show up after attempts at using any command such as 'node-pre-gyp install' or 'node-pre-gyp info'.

`ubuntu@ubuntu:~$ node-pre-gyp info

node-pre-gyp info it worked if it ends with ok

node-pre-gyp info using node-pre-gyp@0.6.30

node-pre-gyp info using node@4.5.0 | linux | arm

node-pre-gyp ERR! UNCAUGHT EXCEPTION

node-pre-gyp ERR! stack Error: Cannot find module 'aws-sdk'

node-pre-gyp ERR! stack     at Function.Module._resolveFilename (module.js:325:15)

node-pre-gyp ERR! stack     at Function.Module._load (module.js:276:25)

node-pre-gyp ERR! stack     at Module.require (module.js:353:17)

node-pre-gyp ERR! stack     at require (internal/module.js:12:17)

node-pre-gyp ERR! stack     at unpublish (/usr/local/lib/node_modules/node-pre-gyp/lib/info.js:14:15)

node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as info] (/usr/local/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)

node-pre-gyp ERR! stack     at run (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)

node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)

node-pre-gyp ERR! stack     at Module._compile (module.js:409:26)

node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)

node-pre-gyp ERR! System Linux 4.4.0-1023-raspi2

node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "info"

node-pre-gyp ERR! cwd /home/ubuntu

node-pre-gyp ERR! node -v v4.5.0

node-pre-gyp ERR! node-pre-gyp -v v0.6.30

node-pre-gyp ERR! This is a bug in `node-pre-gyp`.

node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:

node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>`

Thanks for any help!

**Comment by springmeyer** [comment]
Your installation did not work. `Error: Cannot find module 'aws-sdk'` is the error you need to fix. Try re-installing node-pre-gyp or manually install `aws-sdk`: `npm install aws-sdk`. This is not a problem with node-pre-gyp because `aws-sdk` is properly listed here: https://github.com/mapbox/node-pre-gyp/blob/030ae0c6280f0aedb7eed95cfe7292c46c5e15f4/package.json#L34

**Comment by kerryChen95** [comment]
@springmeyer 
I think `aws-sdk` should be listed as `dependencies` instead of `devDependencies`, because when I install `node-pre-gyp` by `npm install`, `aws-sdk` would not be installed, and then get the error `Cannot resolve module 'aws-sdk'` when use `node-pre-gyp`.

**Comment by kerryChen95** [comment]
It's `node-pre-gyp/lib/info.js:14:14-32` that require `aws-sdk` when `fsevents` use `node-pre-gyp`, so I think `aws-sdk` should be listed as `dependencies` instead of `devDependencies`.

```bash
ERROR in ./app/~/fsevents/~/node-pre-gyp/lib/info.js
Module not found: Error: Cannot resolve module 'aws-sdk' in my-project/app/node_modules/fsevents/node_modules/node-pre-gyp/lib
 @ ./app/~/fsevents/~/node-pre-gyp/lib/info.js 14:14-32
```

**Comment by springmeyer** [comment]
@kerryChen95 `node-pre-gyp/lib/info.js` is only for node-pre-gyp developers. I don't understand why that is being invoked in your case. What is that error message coming from exactly? My opinion is that `aws-sdk` is only a devDependency and is only needed as a devDep as per https://github.com/mapbox/node-pre-gyp#1-add-new-entries-to-your-packagejson

**Comment by kerryChen95** [comment]
@springmeyer 
Sorry, I have just found the fact that it's `webpack` and `fsevents` who together result in this problem.  I use `webpack` to bundle modules including `fsevents` to use them in [Electron](electron.atom.io) environment, but [`fsevents` pass an expression into `require()`](https://github.com/strongloop/fsevents/blob/v1.0.15/fsevents.js#L11), thus [`webpack` parse all files under current directory](http://webpack.github.io/docs/configuration.html#automatically-created-contexts-defaults-module-xxxcontextxxx), for the purpose of knowing what is required recursively. And `node-pre-gyp` is at a sub-directory of `fsevents` becuase `fsevents` declare `node-pre-gyp` as `dependencies`, so `webpack` also parse every file in `node-pre-gyp` including `node-pre-gyp/lib/info.js` then throw the error `Cannot resolve module 'aws-sdk'`.
I have fixed this problem by modifying `webpack` options to not handle the cases like `require(expression)`, since in my case `fsevents` is running in Electron environment, `require(expression)` still works at runtime.

**Comment by KayBeSee** [comment]
@kerryChen95 What exactly did you modify in your webpack options to get that error to go away?

**Comment by kerryChen95** [comment]
@KayBeSee 
I just add below codes as [webpack doc describes](http://webpack.github.io/docs/configuration.html#automatically-created-contexts-defaults-module-xxxcontextxxx), it matches my case.

```
module: {
  // Disable handling of requires with a single expression
  exprContextRegExp: /$^/,
  exprContextCritical: false,
  // Disable handling of requires with expression wrapped by string,
  wrappedContextRegExp: /$^/,
  wrappedContextCritical: false,
}
```

**Comment by kerryChen95** [comment]
@KayBeSee
In my case, the codes `require(expression)` have no need to be pared by webpack, because they run on Node.js(electron's main process), so I disable webpack to handle them.

**Comment by IzaGz** [comment]
@kerryChen95  where have you added the
`module: {
  // Disable handling of requires with a single expression
  exprContextRegExp: /$^/,
  exprContextCritical: false,
  // Disable handling of requires with expression wrapped by string,
  wrappedContextRegExp: /$^/,
  wrappedContextCritical: false,
}`
???

**Comment by relign** [comment]
@kerryChen95 
![image](https://user-images.githubusercontent.com/13749042/45134208-e1d35100-b1cb-11e8-9d30-f4617ae7864a.png)
It will remove....   I have same issue to you.  I want to konw  how to config webpack options???

**Comment by relign** [comment]
![Uploading image.png…]()

`ContextReplacementPlugin`  not support these options
