### ISSUE TITLE
node-pre-gyp for node-ffi modules

### ISSUE THREAD

**Issue by ddavidebor** [mapbox/node-pre-gyp#268]
I have a module that does not use node-pre-gip but uses node-ffi and a dinamic library.

Using `npm pack` i can obtain an installable and working module like the one attached.

Is there a way to use node-pre-gyp with this module, without using gyp itself ? just as a way to manage modules that have binaries.

Maybe a way to specify a particular .tgz to be uploaded.

[data-chan-0.1.1.tgz.zip](https://github.com/mapbox/node-pre-gyp/files/818983/data-chan-0.1.1.tgz.zip)

**Comment by springmeyer** [comment]
@ddavidebor - yes. I can think of two ways to do this:

1) The`node-pre-gyp build` command expects/calls out to node-gyp (which expects a binding.gyp). You could create a binding.gyp whose sole purpose is to download the dynamic library and place it in the right location for node-pre-gyp to package. To do this your `binding.gyp` would have a "target" that simply copies data like https://github.com/mapbox/node-sqlite3/blob/f1456b1cc96e89b82ac37b1896f23ef14aff80b6/binding.gyp#L41-L51 rather than compiles anything
 
2) Alternatively it should work to simply a) manually place your dynamic library in a place node-pre-gyp can find (rather than calling `node-pre-gyp build`) and then b) run `node-pre-gyp package publish, and c) at install time things should work

^^ I realize those are vague instructions. I can give more detail if you need, but wanted to share some quick thoughts. I think 1) feels a little hacky but actually would work well and be able to be automated.

Have you given thought to what platforms you need to support? Do you have a what to compile the `dynamic` library for each platform?

**Comment by ddavidebor** [comment]
Thank you so much! I will poke around following your suggestions :smile:
