### ISSUE TITLE
npm ci returns exit code 1 after running node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by mazyvan** [mapbox/node-pre-gyp#441]
![image](https://user-images.githubusercontent.com/10915753/53208725-6fc9b980-35fd-11e9-9e3c-9d8a9681f0ba.png)

This is everything I get. This does not happen with `npm install` only on `npm ci`

Node: v9.5.0
Npm: 6.7.0
Using nvm: 0.34.0 (this should have nothing to do with it)
OS: Ubuntu 18

I need to use [`npm ci`](https://docs.npmjs.com/cli/ci.html) because is a the deploy server for dev and `npm install` can cause issues

P.S. package.json and package-lock.json are in sync

**Comment by nicolasnoble** [comment]
This is most likely a problem with bcrypt itself, not with node-pre-gyp. The issue generally is that node-pre-gyp needs to be a bundled dependency of the package that uses it to work fine with `npm ci`.

**Comment by mazyvan** [comment]
Sorry seems like it was a problem with the RAM. It wasn't enough. The weird thing was that it stops 🤔 generally the process only get stuck in that kind of situation isn't it?

Anyway thanks for the quick reply

**Comment by nicolasnoble** [comment]
When a machine fully runs out of memory, the kernel enters an OOM killer phase where it'll forcibly terminate processes in order to recover memory. This may be what happened there. You indeed wouldn't get much information beyond the fact the process got killed arbitrarily.

https://linux-mm.org/OOM_Killer
