### ISSUE TITLE
unable to publish to s3 - Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by adnan-kamili** [mapbox/node-pre-gyp#571]
I recently upgraded to the latest verision 1.x from 0.x. Since then unpublish command is crashing

```
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: Cannot read property 'slice' of undefined
node-pre-gyp ERR! stack     at Object.module.exports.detect (/home/runner/work/lexactivator-js/lexactivator-js/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:21:29)
node-pre-gyp ERR! stack     at unpublish (/home/runner/work/lexactivator-js/lexactivator-js/node_modules/@mapbox/node-pre-gyp/lib/unpublish.js:18:12)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as unpublish] (/home/runner/work/lexactivator-js/lexactivator-js/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:81:37)
node-pre-gyp ERR! stack     at run (/home/runner/work/lexactivator-js/lexactivator-js/node_modules/@mapbox/node-pre-gyp/lib/main.js:81:30)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
node-pre-gyp ERR! System Linux 4.15.0-1108-azure
node-pre-gyp ERR! command "/opt/hostedtoolcache/node/12.21.0/x64/bin/node" "/home/runner/work/lexactivator-js/lexactivator-js/node_modules/.bin/node-pre-gyp" "package" "unpublish" "publish" "info"
```

I debugged and in your code it crashes at:

```
if (!config.region) {
    const region = parts[1].slice(1).split('.')[0]; // this line causes the crash
    if (region === 'amazonaws') {
      config.region = 'us-east-1';
    } else {
      config.region = region;
    }
  }

```

**Comment by springmeyer** [comment]
Can you provide the package.json for the application that is using node-pre-gyp? Looks like it is `lexactivator-js`

**Comment by adnan-kamili** [comment]
Yes, here it is:

https://github.com/cryptlex/lexactivator-js/blob/master/package.json

But I had to revert to the 0.x.x version to make it work.

**Comment by springmeyer** [comment]
Got it. So `https://dl.cryptlex.com` is some domain that points to S3? In what region is that hosted? `us-east-1`? The fact that this worked before is a bit of an accident since node-pre-gyp was built to assume that the `host` would be the actual domain name provided by AWS rather than a redirect. So, I'm not quite sure how to repair this functionality yet.

**Comment by springmeyer** [comment]
@adnan-kamili could you try this commit? https://github.com/mapbox/node-pre-gyp/commit/f91bd5317d89d3fafb744055ebc71d32c49b3fc1

**Comment by adnan-kamili** [comment]
It runs in ci/cd, I wonder how to replicate it locally.

**Comment by pive** [comment]
Hi, jumping in because I got the same issue trying to use a minio server instead of s3.
Actually the minio bucket url is like `https://minio.mydomain.com/mybucket`. I tried a workaround by configuring my dns and nginx so that  `https://mybucket.s3-eu-west-3.mydomain.com` is routed to `https://minio.mydomain.com/mybucket`, but node-pre-gyp eventually splits all the url bits and keeps using `amazonaws.com` as the root url:
```
Checking for existing binary at https://mybucket.s3.amazonaws.com/mymodule-v1.0.0-node-v83-win32-x64.tar.gz...
s3 headObject error: "Forbidden: null"
```
Minio is actually compatible with aws-sdk (https://docs.min.io/docs/how-to-use-aws-sdk-for-javascript-with-minio-server.html)
Would it be possible to handle this in the configuration. e.g. instead of providing the `"host"` url, being able to specify the s3 options:
```json
  "binary": {
    "module_name": "mymodule",
    "module_path": "./build",
    "s3": {
      "endpoint": "https://my-aws-endpoint",
      "bucket": "mybucket"
    }
  }
```
I would be happy to submit a PR for this.

**Comment by springmeyer** [comment]
> I would be happy to submit a PR for this.

👍  I would be happy to review a PR that is back compatible (keeps using `host` by default) but if `bucket` or `region` are present will opt-into using those.

**Comment by adnan-kamili** [comment]
I updated to the new version with your recommendations and now I get forbidden error:

https://github.com/cryptlex/lexfloatclient-js/runs/2360080497?check_suite_focus=true

**Comment by springmeyer** [comment]
@adnan-kamili that could be happening either because:

 - You've not provided the right credentials
 - The credentials you've provided are right but the bucket or region is wrong

**Comment by adnan-kamili** [comment]
The same credentials work for the 0.x version. My job is the same, I have just added host and bucket property. The credentials provide full read/write access to all the buckets.

**Comment by pive** [comment]
@adnan-kamili I see your bucket is defined as "dl1.cryptlex.com" in the "binary" section. Can you confirm this is the bucket _name_ and not the bucket url?

**Comment by adnan-kamili** [comment]
Yes, I can confirm this is the bucket name.
