### ISSUE TITLE
Not working with Node.js 15

### ISSUE THREAD

**Issue by adnan-kamili** [mapbox/node-pre-gyp#581]
My app works fine with node-pre-gyp up to Node v14.x. On Node v15.x it fails with the following error:

```
npm ERR! code 127
npm ERR! path /Volumes/Data/xxx/**-js/examples/node_modules/@***/***
npm ERR! command failed
npm ERR! command sh -c ./node_modules/.bin/node-pre-gyp install --fallback-to-build
npm ERR! sh: ./node_modules/.bin/node-pre-gyp: No such file or directory

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*/.npm/_logs/2021-04-16T05_53_48_598Z-debug.log
```

**Comment by bmacnaughton** [comment]
i don't have a windows computer to test on but i am able to install `lexfloatclient` in a skeleton app, on node 15.14.0 on ubuntu 20.04.

@adnan-kamili - can you provide any additional details that would enable us to see what causes node-pre-gyp not to be found in node_modules/.bin?

it's not clear what os, what application is being installed (i guessed lexfloatclient because of a previous post), and some steps about what version of the application to try to install (even if from a github branch)?

**Comment by adnan-kamili** [comment]
I tried this on macOS 11 and docker ubuntu:latest and it failed on both.

**Comment by bmacnaughton** [comment]
can you let me know what specific app you're trying to install? as i mentioned, i was able to install lexfloatclient without error. i don't have enough information to reproduce the error.

**Comment by adnan-kamili** [comment]
It works for npm 6.x but fails for npm v7.9.0

Try installing @cryptlex/lexfloatclient v4.5.2 using npm 7.

**Comment by bmacnaughton** [comment]
thank you for the additional information; i am able to reproduce the problem using npm 7.

the `lexfloatclient` package is a bit odd in that it doesn't have `node-pre-gyp` as a dependency yet it obviously runs it. i will look into this over the weekend.

**Comment by bmacnaughton** [comment]
note: it appears that npm@7 has different behavior when a package is listed in package-lock.json but not in package.json AND (i'm guessing) package-lock.json is older than package.json.

**Comment by springmeyer** [comment]
nice work figuring that out @bmacnaughton 🙇 @adnan-kamili - sounds like the problem is that your `package.json` needs updated. If that does not fix things with npm7, please let us know.

**Comment by adnan-kamili** [comment]
Thanks
