### ISSUE TITLE
node 18 support

### ISSUE THREAD

**Issue by amchiclet** [mapbox/node-pre-gyp#647]
Are there any plans and/or timeline to support node 18? Thank you!

**Comment by ronilan** [comment]
Not sure what the exact issue is but we use `node-pre-gyp` extensively for https://www.npmjs.com/package/@appoptics/apm-bindings and all is OK with node 18 (see: [multi platform test run](https://github.com/appoptics/appoptics-bindings-node/actions/runs/2228440536))

**Comment by amchiclet** [comment]
Good to know. Let me see if I can learn something for your runs.

Here are steps to reproduce in our case (`pprof-nodejs`).

```
$ git clone https://github.com/google/pprof-nodejs.git
$ cd pprof-nodejs/
$ npm install
$ ./node_modules/.bin/node-pre-gyp configure rebuild package --target=18.0.0 --target_arch="x64"

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@18.0.0 | linux | x64
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Unsupported target version: 18.0.0
```

**Comment by ronilan** [comment]
The error is due to the use of the `--target` flag. Since the it relays on "hard coded" values in: https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/abi_crosswalk.json and those have not been updated to node 18 you get the error.

The target flag is for "special cases" (see: https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js#L105) so I'd check to see if you really need those flags for the workflows.

In any case - updating the json is part of the release process (see: https://github.com/mapbox/node-pre-gyp/blob/master/contributing.md). Not sure when this is planned for.

**Comment by amchiclet** [comment]
Looking at [this code](https://github.com/mapbox/node-pre-gyp/blob/eb1ec94913cbb72acbf2a4dc69896581d131fef8/lib/util/versioning.js#L88-L90), it means while waiting for the crosswalk file to catch up with node 18, I could achieve the same effect as

`./node_modules/.bin/node-pre-gyp configure rebuild package --target=18.0.0 --target_arch="x64"`

by running

`./node_modules/.bin/node-pre-gyp configure rebuild package

on an x64 machine with node 18.0.0 active.

Is my understanding correct?

**Comment by nolanmar511** [comment]
The `--target` flag is definitely super useful for how we are creating pre-built binaries in github.com/google/pprof-nodejs (it allows us to generate pre-built binaries without installing multiple versions of the Node.js on the machine generating the prebuilt binaries).

Is there a path to getting #649 submitted, or should we plan to change how we build pre-built binaries if we'd like to add support for Node 18?

**Comment by ronilan** [comment]
@nolanmar511 you are aware of #657 right?

**Comment by rbirkgit** [comment]
I am having issues with Node 18 as well. Getting errors when installing `nodejieba`

**Comment by cclauss** [comment]
For support of Node.js > v17, see the workaround:
* #710
