### ISSUE TITLE
Vulnerability warning due to make-dir version

### ISSUE THREAD

**Issue by AkiraMiyakoda** [mapbox/node-pre-gyp#685]
Hi developers,

Currently, this package receives a vulnerability warning concerning [CVE-2022-25883](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) reported a few days ago.
This package depends on `make-dir` which [has been updated](https://github.com/sindresorhus/make-dir/issues/39) in order to fix that warning. So I think that `node-pre-gyp` should be updated to depend on the new version of `make-dir`. 

Here is what I received:
```
semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install argon2@0.27.1, which is a breaking change
node_modules/make-dir/node_modules/semver
  make-dir  2.0.0 - 3.1.0
  Depends on vulnerable versions of semver
  node_modules/make-dir
    @mapbox/node-pre-gyp  >=1.0.1
    Depends on vulnerable versions of make-dir
    node_modules/@mapbox/node-pre-gyp
      argon2  >=0.27.2
      Depends on vulnerable versions of @mapbox/node-pre-gyp
      node_modules/argon2

4 moderate severity vulnerabilities
```

**Comment by striezel** [comment]
It looks like the package is a bit slow to update its dependencies, so maybe semi-automated dependency updates via [Dependabot](https://docs.github.com/de/code-security/dependabot/dependabot-version-updates) or a similar mechanism can help here. That's why I opened a PR that adds a Dependabot configuration (https://github.com/mapbox/node-pre-gyp/pull/688).

**Comment by ranisalt** [comment]
@striezel _very_ slow. Last version was in September, seems completely abandoned ever since (issues/PRs get no response). I'm looking to remove it from node-argon2

**Comment by striezel** [comment]
> seems completely abandoned ever since (issues/PRs get no response).

That is sad. :(
If the repository is abandoned, then moving away from it seems to be the right action. However, I'm hoping that somebody @mapbox will pick this up and get the issues fixed and PRs merged and publish a new version to NPM, because not everyone might be able to completely remove @mapbox/node-pre-gyp from package dependencies.

**Comment by prashant93** [comment]
Team any update on semver vulnerablility fix : CVE-2022-25883

**Comment by axrj** [comment]
Hey all, apologies for the delays. Will get this patched soon.

**Comment by sagar-sonawane-ma** [comment]
@axrj can you please share the issue ID link for the fix, where we can trace the same for the feature release.

**Comment by axrj** [comment]
- Fixed in https://github.com/mapbox/node-pre-gyp/pull/691
