### ISSUE TITLE
Error: Unsupported target versions: Node.js > v17

### ISSUE THREAD

**Issue by cclauss** [mapbox/node-pre-gyp#710]
* #657
# __WORKAROUND:__ To support newer versions of Node.js > v17
```
npm ci  # mapbox/node-pre-gyp
npm run update-crosswalk
```
---
`abi_crosswalk.json` must be updated to cover all currently supported versions of Node.js.
https://github.com/mapbox/node-pre-gyp/blob/a74f5e367c0d71033620aa0112e7baf7f3515b9d/lib/util/abi_crosswalk.json#L2598

Proof:
* #709

The testing on this repo fails on all currently supported versions of Node.js but passes on end-of-life versions.
* https://github.com/nodejs/release#release-schedule

@springmeyer @ewanharris, @mapsam

**Comment by ewanharris** [comment]
@cclauss I think node-pre-gyp can be viewed as having no maintenance due to #657. I was never associated with the package, just made PRs as needed, and since that issue I ended up using [patch-package](https://www.npmjs.com/package/patch-package) to maintain updates to the abi_crosswalk.json file [there](https://github.com/tidev/node-ios-device/tree/1_X/patches), it's not ideal but AFAICT it's the only path forward for users right now.

At 6.5 million weekly downloads and >1000 dependents (across `@mapbox/node-pre-gyp` and `node-pre-gyp`) it's clear this package is well used in the ecosystem but given that mapbox no longer uses this software could it potentially be picked up in some manner by the Node.js project?

**Comment by cclauss** [comment]
Fixed in #711 but perhaps not yet released.  https://github.com/mapbox/node-pre-gyp/tags
* #711
