### ISSUE TITLE
Needed: A GitHub Action to package and publish a new version

### ISSUE THREAD

**Issue by cclauss** [mapbox/node-pre-gyp#739]
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#packaging-workflow-data-as-artifacts

-->
*  #744

**Comment by acalcutt** [comment]
In maplibre-native workflow we settled on this workflow that checks if the version in package.json is published. 
https://github.com/maplibre/maplibre-native/blob/main/.github/workflows/node-release.yml#L9-L34

If it is not published it runs the build
https://github.com/maplibre/maplibre-native/blob/main/.github/workflows/node-release.yml#L38

maybe something like that would work here. Seems like it would be easier because this project doesn't really need to build anything, just run the publish steps.
https://github.com/maplibre/maplibre-native/blob/main/.github/workflows/node-release.yml#L304-L310

**Comment by cclauss** [comment]
Cool!  Pull requests will be reviewed.  Let's see how that approach works.

**Comment by mapsam** [comment]
I'm in favor of GitHub release for this as well. This may be blocked by using the `@mapbox/node-pre-gyp` namespace for a bit, since the Mapbox NPM scope is pretty locked down and I'm not sure we'll be able to grant tokens for public repositories like this. Ultimately this is a good argument to move back to the unscoped `node-pre-gyp` NPM module which does not have the same security restrictions.

Not ideal, but in the short-term I can cut one-off prereleases for `@mapbox/node-pre-gyp` as needed @cclauss

**Comment by cclauss** [comment]
I understand the complexities.  I think we need a pre-release and then a release BEFORE we merge other changes (all the Dependabot changes, etc.).  Please proceed with that pre-release when you feel comfortable doing so.

**Comment by mapsam** [comment]
Sounds good! Can you give me a commit to prerelease from? Just want to make sure I release what you're expecting. Latest master is https://github.com/mapbox/node-pre-gyp/commit/13d4ac74853070cd2a9649e1f8079e5d68839c7a

**Comment by mapsam** [comment]
`@mapbox/node-pre-gyp@1.1.0-dev.1` has been published from https://github.com/mapbox/node-pre-gyp/commit/13d4ac74853070cd2a9649e1f8079e5d68839c7a.

I need to push package.json version changes to GitHub in order to publish to the `@mapbox/` namespace, so technically the version is published from https://github.com/mapbox/node-pre-gyp/commit/996b31b06800d384e893c1108b7e8796cb97cd8f. 

I'll use https://github.com/mapbox/node-pre-gyp/tree/mapsam/v1.1.0-pre and keep it in sync with `master` as you need more dev releases and until the GitHub Actions work is set up.
